version: '3'
services:

  orders-ms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
    depends_on:
      - postgres
    networks:
      - eshop

  postgres:
    image: postgres:latest
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=test
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - eshop


networks:
  eshop:
    external: true

volumes:
  postgres-data: